name: cashier_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  image_picker: ^1.0.5
  blue_thermal_printer: ^1.1.5
  pdf: ^3.10.4
  path_provider: ^2.0.14
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/bg.jpg
  uses-material-design: true
